require 'addressable/template'
require 'oauth2'
require 'faraday_middleware'
require 'active_support/all'

require 'skroutz_api/version'

module SkroutzApi
  autoload :Client, 'skroutz_api/client'
  autoload :Default, 'skroutz_api/default'
  autoload :Parsing, 'skroutz_api/parsing'
  autoload :Resource, 'skroutz_api/resource'
  autoload :UrlHelpers, 'skroutz_api/url_helpers'
  autoload :CollectionProxy, 'skroutz_api/collection_proxy'
  autoload :Category, 'skroutz_api/category'
  autoload :CategoriesCollection, 'skroutz_api/categories_collection'
  autoload :Sku, 'skroutz_api/sku'
  autoload :SkusCollection, 'skroutz_api/skus_collection'
  autoload :Product, 'skroutz_api/product'
  autoload :ProductsCollection, 'skroutz_api/products_collection'
  autoload :Shop, 'skroutz_api/shop'
  autoload :Manufacturer, 'skroutz_api/manufacturer'
  autoload :Search, 'skroutz_api/search'
  autoload :FilterGroup, 'skroutz_api/filter_group'
  autoload :Favorite, 'skroutz_api/favorite'
  autoload :Notification, 'skroutz_api/notification'
  autoload :PaginatedCollection, 'skroutz_api/paginated_collection'
end
